<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ramón Martínez, Rodrigo Rabanal">

<title>Práctica 1 estadística</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Practica1_estadistica_files/libs/clipboard/clipboard.min.js"></script>
<script src="Practica1_estadistica_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Practica1_estadistica_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Practica1_estadistica_files/libs/quarto-html/popper.min.js"></script>
<script src="Practica1_estadistica_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Practica1_estadistica_files/libs/quarto-html/anchor.min.js"></script>
<link href="Practica1_estadistica_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Practica1_estadistica_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Practica1_estadistica_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Practica1_estadistica_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Practica1_estadistica_files/libs/bootstrap/bootstrap-2a5858aadb409879eface58f2bab4920.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="estilos.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#exploración-inicial" id="toc-exploración-inicial" class="nav-link active" data-scroll-target="#exploración-inicial">1. EXPLORACIÓN INICIAL</a>
  <ul class="collapse">
  <li><a href="#media-mediana-y-desviación-típica" id="toc-media-mediana-y-desviación-típica" class="nav-link" data-scroll-target="#media-mediana-y-desviación-típica">1. Media, mediana y desviación típica</a></li>
  <li><a href="#histograma-de-la-variable-performance_index" id="toc-histograma-de-la-variable-performance_index" class="nav-link" data-scroll-target="#histograma-de-la-variable-performance_index">2. Histograma de la variable <em>performance_index</em></a></li>
  <li><a href="#distribución-de-frecuencias-relativas" id="toc-distribución-de-frecuencias-relativas" class="nav-link" data-scroll-target="#distribución-de-frecuencias-relativas">3. Distribución de frecuencias relativas</a></li>
  <li><a href="#diagrama-de-cajas-de-performace_index-según-el-equipo" id="toc-diagrama-de-cajas-de-performace_index-según-el-equipo" class="nav-link" data-scroll-target="#diagrama-de-cajas-de-performace_index-según-el-equipo">4. Diagrama de cajas de <em>performace_index</em> según el equipo</a></li>
  <li><a href="#gráfico-de-dispersión-entre-training_hours-y-performance_index" id="toc-gráfico-de-dispersión-entre-training_hours-y-performance_index" class="nav-link" data-scroll-target="#gráfico-de-dispersión-entre-training_hours-y-performance_index">5. Gráfico de dispersión entre <em>training_hours</em> y <em>performance_index</em></a></li>
  <li><a href="#matriz-de-correlaciones" id="toc-matriz-de-correlaciones" class="nav-link" data-scroll-target="#matriz-de-correlaciones">6. Matriz de correlaciones</a></li>
  <li><a href="#gráfico-de-dispersión-entre-fatiga-e-índice-de-rendimiento" id="toc-gráfico-de-dispersión-entre-fatiga-e-índice-de-rendimiento" class="nav-link" data-scroll-target="#gráfico-de-dispersión-entre-fatiga-e-índice-de-rendimiento">7. Gráfico de dispersión entre fatiga e índice de rendimiento</a></li>
  <li><a href="#boxplot-del-índice-de-rendimiento-por-posición" id="toc-boxplot-del-índice-de-rendimiento-por-posición" class="nav-link" data-scroll-target="#boxplot-del-índice-de-rendimiento-por-posición">8. Boxplot del índice de rendimiento por posición</a></li>
  <li><a href="#valores-atípicos-en-agility_time" id="toc-valores-atípicos-en-agility_time" class="nav-link" data-scroll-target="#valores-atípicos-en-agility_time">9. Valores atípicos en <em>agility_time</em></a></li>
  <li><a href="#proporción-de-jugadores-zurdos-en-la-base-de-datos" id="toc-proporción-de-jugadores-zurdos-en-la-base-de-datos" class="nav-link" data-scroll-target="#proporción-de-jugadores-zurdos-en-la-base-de-datos">10. Proporción de jugadores zurdos en la base de datos</a></li>
  </ul></li>
  <li><a href="#manejo-de-valores-faltantes" id="toc-manejo-de-valores-faltantes" class="nav-link" data-scroll-target="#manejo-de-valores-faltantes">2. MANEJO DE VALORES FALTANTES</a>
  <ul class="collapse">
  <li><a href="#identificación-de-variables-con-valores-faltantes" id="toc-identificación-de-variables-con-valores-faltantes" class="nav-link" data-scroll-target="#identificación-de-variables-con-valores-faltantes">1. Identificación de variables con valores faltantes</a></li>
  <li><a href="#calculamos-la-proporción-de-valores-faltantes-sobre-el-dataset-completo" id="toc-calculamos-la-proporción-de-valores-faltantes-sobre-el-dataset-completo" class="nav-link" data-scroll-target="#calculamos-la-proporción-de-valores-faltantes-sobre-el-dataset-completo">2. Calculamos la proporción de valores faltantes sobre el dataset completo</a></li>
  <li><a href="#resumen-de-combina-las-variables-con-missing-y-su-porcentaje-de-valores-ausentes" id="toc-resumen-de-combina-las-variables-con-missing-y-su-porcentaje-de-valores-ausentes" class="nav-link" data-scroll-target="#resumen-de-combina-las-variables-con-missing-y-su-porcentaje-de-valores-ausentes">3. Resumen de combina las variables con missing y su porcentaje de valores ausentes</a></li>
  <li><a href="#imputación-por-la-media-en-training_hours" id="toc-imputación-por-la-media-en-training_hours" class="nav-link" data-scroll-target="#imputación-por-la-media-en-training_hours">4. Imputación por la media en <em>training_hours</em></a></li>
  <li><a href="#histogramas-de-sleep_hours-antes-y-después-de-la-imputación-por-la-media" id="toc-histogramas-de-sleep_hours-antes-y-después-de-la-imputación-por-la-media" class="nav-link" data-scroll-target="#histogramas-de-sleep_hours-antes-y-después-de-la-imputación-por-la-media">5. Histogramas de <em>sleep_hours</em> antes y después de la imputación por la media</a></li>
  <li><a href="#imputación-por-la-mediana-en-fatigue-y-comparación-con-imputación-con-la-media." id="toc-imputación-por-la-mediana-en-fatigue-y-comparación-con-imputación-con-la-media." class="nav-link" data-scroll-target="#imputación-por-la-mediana-en-fatigue-y-comparación-con-imputación-con-la-media.">6. Imputación por la mediana en <em>fatigue</em> y comparación con imputación con la media.</a></li>
  <li><a href="#imputación-condicional-en-strength_1rm" id="toc-imputación-condicional-en-strength_1rm" class="nav-link" data-scroll-target="#imputación-condicional-en-strength_1rm">7. Imputación condicional en <em>strength_1RM</em></a></li>
  <li><a href="#comentario-acerca-de-los-valores-faltantes" id="toc-comentario-acerca-de-los-valores-faltantes" class="nav-link" data-scroll-target="#comentario-acerca-de-los-valores-faltantes">8. Comentario acerca de los valores faltantes</a></li>
  <li><a href="#modelo-lineal-simple-entre-performance_index-y-training_hours" id="toc-modelo-lineal-simple-entre-performance_index-y-training_hours" class="nav-link" data-scroll-target="#modelo-lineal-simple-entre-performance_index-y-training_hours">9. Modelo lineal simple entre <em>performance_index</em> y <em>training_hours</em></a></li>
  <li><a href="#modelo-lineal-con-valores-imputados" id="toc-modelo-lineal-con-valores-imputados" class="nav-link" data-scroll-target="#modelo-lineal-con-valores-imputados">10. Modelo lineal con valores imputados</a></li>
  </ul></li>
  <li><a href="#regresión-lineal-simple-y-múltiple" id="toc-regresión-lineal-simple-y-múltiple" class="nav-link" data-scroll-target="#regresión-lineal-simple-y-múltiple">3. REGRESIÓN LINEAL SIMPLE Y MÚLTIPLE</a>
  <ul class="collapse">
  <li><a href="#modelo-de-regresión-lineal-simple-entre-performance_index-y-training_hours" id="toc-modelo-de-regresión-lineal-simple-entre-performance_index-y-training_hours" class="nav-link" data-scroll-target="#modelo-de-regresión-lineal-simple-entre-performance_index-y-training_hours">1. Modelo de regresión lineal simple entre <em>performance_index</em> y <em>training_hours</em></a></li>
  <li><a href="#gráfico-de-dispersión-del-modelo" id="toc-gráfico-de-dispersión-del-modelo" class="nav-link" data-scroll-target="#gráfico-de-dispersión-del-modelo">2. Gráfico de dispersión del modelo</a></li>
  <li><a href="#cálculo-y-análisis-del-r2-del-modelo" id="toc-cálculo-y-análisis-del-r2-del-modelo" class="nav-link" data-scroll-target="#cálculo-y-análisis-del-r2-del-modelo">3. Cálculo y análisis del R^2 del modelo</a></li>
  <li><a href="#modelo-de-regresión-lineal-múltiple" id="toc-modelo-de-regresión-lineal-múltiple" class="nav-link" data-scroll-target="#modelo-de-regresión-lineal-múltiple">4. Modelo de regresión lineal múltiple</a></li>
  <li><a href="#comparación-con-el-modelo-simple" id="toc-comparación-con-el-modelo-simple" class="nav-link" data-scroll-target="#comparación-con-el-modelo-simple">5. Comparación con el modelo simple</a></li>
  <li><a href="#adición-de-la-variable-fatigue" id="toc-adición-de-la-variable-fatigue" class="nav-link" data-scroll-target="#adición-de-la-variable-fatigue">6. Adición de la variable <em>fatigue</em></a></li>
  <li><a href="#efecto-de-la-variable-position" id="toc-efecto-de-la-variable-position" class="nav-link" data-scroll-target="#efecto-de-la-variable-position">7. Efecto de la variable <em>position</em></a></li>
  <li><a href="#incluimos-sleep_hours-como-predictor-adicional" id="toc-incluimos-sleep_hours-como-predictor-adicional" class="nav-link" data-scroll-target="#incluimos-sleep_hours-como-predictor-adicional">8. Incluimos <em>sleep_hours</em> como predictor adicional</a></li>
  <li><a href="#diagrama-de-residuos-del-modelo-múltiple" id="toc-diagrama-de-residuos-del-modelo-múltiple" class="nav-link" data-scroll-target="#diagrama-de-residuos-del-modelo-múltiple">9. Diagrama de residuos del modelo múltiple</a></li>
  <li><a href="#modelo-lineal-simple-vs-múltiple" id="toc-modelo-lineal-simple-vs-múltiple" class="nav-link" data-scroll-target="#modelo-lineal-simple-vs-múltiple">10. Modelo lineal simple vs múltiple</a></li>
  </ul></li>
  <li><a href="#no-linealidades-y-piecewise" id="toc-no-linealidades-y-piecewise" class="nav-link" data-scroll-target="#no-linealidades-y-piecewise">4. NO LINEALIDADES Y PIECEWISE</a>
  <ul class="collapse">
  <li><a href="#modelo-no-lineal" id="toc-modelo-no-lineal" class="nav-link" data-scroll-target="#modelo-no-lineal">1. Modelo no lineal</a></li>
  <li><a href="#relación-entre-performance_index-y-age" id="toc-relación-entre-performance_index-y-age" class="nav-link" data-scroll-target="#relación-entre-performance_index-y-age">2. Relación entre <em>performance_index</em> y <em>age</em></a></li>
  <li><a href="#variable-dicotómica-para-sleep_hours" id="toc-variable-dicotómica-para-sleep_hours" class="nav-link" data-scroll-target="#variable-dicotómica-para-sleep_hours">3. Variable dicotómica para <em>sleep_hours</em></a></li>
  <li><a href="#performance_index-frente-a-fatigue-empleando-un-loess" id="toc-performance_index-frente-a-fatigue-empleando-un-loess" class="nav-link" data-scroll-target="#performance_index-frente-a-fatigue-empleando-un-loess">4. <em>performance_index</em> frente a <em>fatigue</em> empleando un LOESS</a></li>
  <li><a href="#spline-sobre-training_hours-y-comparación-con-método-cuadrático" id="toc-spline-sobre-training_hours-y-comparación-con-método-cuadrático" class="nav-link" data-scroll-target="#spline-sobre-training_hours-y-comparación-con-método-cuadrático">5. Spline sobre <em>training_hours</em> y comparación con método cuadrático</a></li>
  <li><a href="#piecewise-en-travel_km_week" id="toc-piecewise-en-travel_km_week" class="nav-link" data-scroll-target="#piecewise-en-travel_km_week">6. Piecewise en travel_km_week</a></li>
  <li><a href="#evaluación-del-aic-entre-modelos-lineal-cuadrático-y-piecewise-para-training_hours" id="toc-evaluación-del-aic-entre-modelos-lineal-cuadrático-y-piecewise-para-training_hours" class="nav-link" data-scroll-target="#evaluación-del-aic-entre-modelos-lineal-cuadrático-y-piecewise-para-training_hours">7. Evaluación del AIC entre modelos lineal, cuadrático y piecewise para <em>training_hours</em></a></li>
  <li><a href="#representación-gráfica-de-las-predicciones-del-modelo-piecewise-frente-a-las-observaciones-reales" id="toc-representación-gráfica-de-las-predicciones-del-modelo-piecewise-frente-a-las-observaciones-reales" class="nav-link" data-scroll-target="#representación-gráfica-de-las-predicciones-del-modelo-piecewise-frente-a-las-observaciones-reales">8. Representación gráfica de las predicciones del modelo piecewise frente a las observaciones reales</a></li>
  <li><a href="#ajuste-de-modelo-lineal-simple-con-casos-completos" id="toc-ajuste-de-modelo-lineal-simple-con-casos-completos" class="nav-link" data-scroll-target="#ajuste-de-modelo-lineal-simple-con-casos-completos">9. Ajuste de modelo lineal simple con casos completos</a></li>
  <li><a href="#modelo-con-dataset-imputado" id="toc-modelo-con-dataset-imputado" class="nav-link" data-scroll-target="#modelo-con-dataset-imputado">10. Modelo con dataset imputado</a></li>
  </ul></li>
  <li><a href="#heterocedasticidad" id="toc-heterocedasticidad" class="nav-link" data-scroll-target="#heterocedasticidad">5. HETEROCEDASTICIDAD</a>
  <ul class="collapse">
  <li><a href="#ajuste-de-modelo-múltiple-con-gráfico-de-residuos" id="toc-ajuste-de-modelo-múltiple-con-gráfico-de-residuos" class="nav-link" data-scroll-target="#ajuste-de-modelo-múltiple-con-gráfico-de-residuos">1. Ajuste de modelo múltiple con gráfico de residuos</a></li>
  <li><a href="#test-de-breusch-pagan" id="toc-test-de-breusch-pagan" class="nav-link" data-scroll-target="#test-de-breusch-pagan">2. Test de Breusch-Pagan</a></li>
  <li><a href="#varianza-de-los-residuos-en-la-variable-fatigue" id="toc-varianza-de-los-residuos-en-la-variable-fatigue" class="nav-link" data-scroll-target="#varianza-de-los-residuos-en-la-variable-fatigue">3. Varianza de los residuos en la variable <em>fatigue</em></a></li>
  <li><a href="#gráfica-de-residuos-vs-sleep_hours" id="toc-gráfica-de-residuos-vs-sleep_hours" class="nav-link" data-scroll-target="#gráfica-de-residuos-vs-sleep_hours">4. Gráfica de residuos vs <em>sleep_hours</em></a></li>
  <li><a href="#modelo-con-errores-estándar-robusto-hc" id="toc-modelo-con-errores-estándar-robusto-hc" class="nav-link" data-scroll-target="#modelo-con-errores-estándar-robusto-hc">5. Modelo con errores estándar robusto (HC)</a></li>
  <li><a href="#transformación-logarítmica-al-predictor-travel_km_week" id="toc-transformación-logarítmica-al-predictor-travel_km_week" class="nav-link" data-scroll-target="#transformación-logarítmica-al-predictor-travel_km_week">6. Transformación logarítmica al predictor <em>travel_km_week</em></a></li>
  <li><a href="#estudio-gráfico-sobre-la-causa-de-la-heterocedasticidad" id="toc-estudio-gráfico-sobre-la-causa-de-la-heterocedasticidad" class="nav-link" data-scroll-target="#estudio-gráfico-sobre-la-causa-de-la-heterocedasticidad">7. Estudio gráfico sobre la causa de la heterocedasticidad</a></li>
  <li><a href="#cómo-afecta-la-heterocedasticidad" id="toc-cómo-afecta-la-heterocedasticidad" class="nav-link" data-scroll-target="#cómo-afecta-la-heterocedasticidad">8. Cómo afecta la heterocedasticidad</a></li>
  <li><a href="#posibilidad-de-recurrir-a-un-glm-con-varianza-distinta-a-la-normal-para-modelar-performance_index" id="toc-posibilidad-de-recurrir-a-un-glm-con-varianza-distinta-a-la-normal-para-modelar-performance_index" class="nav-link" data-scroll-target="#posibilidad-de-recurrir-a-un-glm-con-varianza-distinta-a-la-normal-para-modelar-performance_index">9. Posibilidad de recurrir a un GLM con varianza distinta a la normal para modelar <em>performance_index</em></a></li>
  <li><a href="#estrategia-más-adecuada" id="toc-estrategia-más-adecuada" class="nav-link" data-scroll-target="#estrategia-más-adecuada">10. Estrategia más adecuada</a></li>
  </ul></li>
  <li><a href="#modelos-glm" id="toc-modelos-glm" class="nav-link" data-scroll-target="#modelos-glm">6. MODELOS GLM</a>
  <ul class="collapse">
  <li><a href="#modelo-de-poisson-para-injury_count" id="toc-modelo-de-poisson-para-injury_count" class="nav-link" data-scroll-target="#modelo-de-poisson-para-injury_count">1. Modelo de Poisson para <em>injury_count</em></a></li>
  <li><a href="#existencia-de-sobre-dispersión-en-el-modelo-de-poisson" id="toc-existencia-de-sobre-dispersión-en-el-modelo-de-poisson" class="nav-link" data-scroll-target="#existencia-de-sobre-dispersión-en-el-modelo-de-poisson">2. Existencia de sobre-dispersión en el modelo de Poisson</a></li>
  <li><a href="#modelo-de-binomial-negativa" id="toc-modelo-de-binomial-negativa" class="nav-link" data-scroll-target="#modelo-de-binomial-negativa">3. Modelo de binomial negativa</a></li>
  <li><a href="#comparación-de-la-devianza-residual-de-los-modelos-de-poisson-y-negbin" id="toc-comparación-de-la-devianza-residual-de-los-modelos-de-poisson-y-negbin" class="nav-link" data-scroll-target="#comparación-de-la-devianza-residual-de-los-modelos-de-poisson-y-negbin">4. Comparación de la devianza residual de los modelos de Poisson y NegBin</a></li>
  <li><a href="#ratios-para-modelo-de-regresión-logística" id="toc-ratios-para-modelo-de-regresión-logística" class="nav-link" data-scroll-target="#ratios-para-modelo-de-regresión-logística">5. Ratios para modelo de regresión logística</a></li>
  <li><a href="#representación-de-curva-roc-y-cálculo-del-auc" id="toc-representación-de-curva-roc-y-cálculo-del-auc" class="nav-link" data-scroll-target="#representación-de-curva-roc-y-cálculo-del-auc">6. Representación de curva ROC y cálculo del AUC</a></li>
  <li><a href="#modelo-binomial-logit-para-la-tasa-de-acierto-en-pases" id="toc-modelo-binomial-logit-para-la-tasa-de-acierto-en-pases" class="nav-link" data-scroll-target="#modelo-binomial-logit-para-la-tasa-de-acierto-en-pases">7. Modelo binomial logit para la tasa de acierto en pases</a></li>
  <li><a href="#qué-posición-tiene-mayor-probabilidad-de-completar-pases-exitosos" id="toc-qué-posición-tiene-mayor-probabilidad-de-completar-pases-exitosos" class="nav-link" data-scroll-target="#qué-posición-tiene-mayor-probabilidad-de-completar-pases-exitosos">8. Qué posición tiene mayor probabilidad de completar pases exitosos</a></li>
  <li><a href="#modelo-logístico-incluyendo-sleep_hours" id="toc-modelo-logístico-incluyendo-sleep_hours" class="nav-link" data-scroll-target="#modelo-logístico-incluyendo-sleep_hours">9. Modelo logístico incluyendo sleep_hours</a></li>
  <li><a href="#ventajas-de-usar-glm-frente-a-la-regresión-lineal-para-modelar-variables-como-lesiones-titularidad-o-éxito-en-pases." id="toc-ventajas-de-usar-glm-frente-a-la-regresión-lineal-para-modelar-variables-como-lesiones-titularidad-o-éxito-en-pases." class="nav-link" data-scroll-target="#ventajas-de-usar-glm-frente-a-la-regresión-lineal-para-modelar-variables-como-lesiones-titularidad-o-éxito-en-pases.">10. Ventajas de usar GLM frente a la regresión lineal para modelar variables como lesiones, titularidad o éxito en pases.</a></li>
  </ul></li>
  <li><a href="#interacciones" id="toc-interacciones" class="nav-link" data-scroll-target="#interacciones">7. INTERACCIONES</a>
  <ul class="collapse">
  <li><a href="#ajuste-de-modelo-lineal-para-performance_index-en-función-de-training_hoursxmatch_intensity" id="toc-ajuste-de-modelo-lineal-para-performance_index-en-función-de-training_hoursxmatch_intensity" class="nav-link" data-scroll-target="#ajuste-de-modelo-lineal-para-performance_index-en-función-de-training_hoursxmatch_intensity">1. Ajuste de modelo lineal para <em>performance_index</em> en función de <em>training_hours</em>X<em>match_intensity</em></a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Práctica 1 estadística</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ramón Martínez, Rodrigo Rabanal </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p><img src="logo.png" class="logo"></p>
<section id="exploración-inicial" class="level1">
<h1>1. EXPLORACIÓN INICIAL</h1>
<p>Antes de empezar, cargamos las librerías que vamos a usar.</p>
<p>Empezaremos planteando una visualización de los datos, para entender la naturaleza de las variables y ver los valores con los que trabajaremos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> performance_index injuries_count      starter        passes_attempted
 Min.   :27.27     Min.   :0.0000   Min.   :0.00000   Min.   : 10.00  
 1st Qu.:53.06     1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.: 34.00  
 Median :59.93     Median :0.0000   Median :0.00000   Median : 56.00  
 Mean   :59.23     Mean   :0.3321   Mean   :0.02111   Mean   : 55.66  
 3rd Qu.:66.40     3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.: 78.00  
 Max.   :82.62     Max.   :4.0000   Max.   :1.00000   Max.   :100.00  
                                                                      
 passes_success       age        training_hours  match_intensity 
 Min.   : 0.00   Min.   :17.00   Min.   : 4.26   Min.   : 30.00  
 1st Qu.:14.00   1st Qu.:22.00   1st Qu.:11.26   1st Qu.: 63.60  
 Median :25.00   Median :26.00   Median :13.75   Median : 70.30  
 Mean   :26.53   Mean   :26.45   Mean   :13.69   Mean   : 70.77  
 3rd Qu.:37.00   3rd Qu.:31.00   3rd Qu.:15.95   3rd Qu.: 78.70  
 Max.   :77.00   Max.   :36.00   Max.   :24.75   Max.   :100.00  
                                 NA's   :5                       
   position          sleep_hours     travel_km_week      fatigue     
 Length:521         Min.   : 4.470   Min.   :   0.0   Min.   :10.00  
 Class :character   1st Qu.: 6.577   1st Qu.: 362.6   1st Qu.:39.52  
 Mode  :character   Median : 7.210   Median : 833.3   Median :49.30  
                    Mean   : 7.184   Mean   : 822.5   Mean   :49.40  
                    3rd Qu.: 7.780   3rd Qu.:1217.5   3rd Qu.:59.73  
                    Max.   :10.000   Max.   :3028.4   Max.   :93.20  
                    NA's   :5                         NA's   :5      
  strength_1RM    agility_time   nutrition_score      team          
 Min.   : 80.0   Min.   : 9.00   Min.   : 2.200   Length:521        
 1st Qu.:133.0   1st Qu.:10.74   1st Qu.: 5.700   Class :character  
 Median :149.7   Median :11.45   Median : 6.700   Mode  :character  
 Mean   :149.2   Mean   :11.47   Mean   : 6.772                     
 3rd Qu.:164.9   3rd Qu.:12.21   3rd Qu.: 7.900                     
 Max.   :217.2   Max.   :14.26   Max.   :10.000                     
 NA's   :5       NA's   :5                                          
  left_footed     previous_injuries altitude_home   
 Min.   :0.0000   Min.   : 0.000    Min.   :   0.0  
 1st Qu.:0.0000   1st Qu.: 0.000    1st Qu.: 269.2  
 Median :0.0000   Median : 1.000    Median : 472.6  
 Mean   :0.2917   Mean   : 2.296    Mean   : 482.0  
 3rd Qu.:1.0000   3rd Qu.: 3.000    3rd Qu.: 669.5  
 Max.   :1.0000   Max.   :29.000    Max.   :1445.0  
                                                    </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   521 obs. of  19 variables:
 $ performance_index: num  64.4 65.7 70.2 58.1 73.3 ...
 $ injuries_count   : int  3 2 0 0 0 0 1 0 0 0 ...
 $ starter          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ passes_attempted : int  53 56 87 88 49 93 13 18 70 71 ...
 $ passes_success   : int  15 25 45 44 24 47 8 9 45 32 ...
 $ age              : int  25 36 36 24 36 33 29 33 32 36 ...
 $ training_hours   : num  11.3 13.2 14.1 13 18 ...
 $ match_intensity  : num  79.6 70.3 66.5 64.5 75 66 81.5 70.8 66.6 58.8 ...
 $ position         : chr  "Forward" "Defender" "Defender" "Midfielder" ...
 $ sleep_hours      : num  6.86 7.29 8.49 7 9.01 6.71 8.31 7.43 8.06 6.36 ...
 $ travel_km_week   : num  414 236 267 1297 1315 ...
 $ fatigue          : num  59.8 57.4 43.1 56.4 42.5 68.2 56 49.1 18.6 61.9 ...
 $ strength_1RM     : num  131 133 154 131 169 ...
 $ agility_time     : num  12.1 10.8 11.8 10.6 11.6 ...
 $ nutrition_score  : num  5.9 7.8 6.9 6.2 6.2 6.4 5.9 6.7 7.3 6 ...
 $ team             : chr  "Team C" "Team B" "Team C" "Team B" ...
 $ left_footed      : int  1 0 0 0 1 0 0 0 0 1 ...
 $ previous_injuries: int  0 0 1 0 4 1 1 0 0 0 ...
 $ altitude_home    : num  840 717 560 1055 358 ...</code></pre>
</div>
</div>
<p>Vamos a realizar un pequeño análisis exploratorio de datos, atendiendo a diferentes aspectos de los mismos.</p>
<section id="media-mediana-y-desviación-típica" class="level2">
<h2 class="anchored" data-anchor-id="media-mediana-y-desviación-típica">1. Media, mediana y desviación típica</h2>
<p>En primer lugar, calcularemos la media, la mediana y la desviación típica del índice de rendimiento de los jugadores.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 59.23209</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 59.93</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.784195</code></pre>
</div>
</div>
<p>Se aprecia una media y una mediana parecidas, lo que parece indicar que la mayoría de jugadores se encuentran en un estado de forma relativamente similar.</p>
</section>
<section id="histograma-de-la-variable-performance_index" class="level2">
<h2 class="anchored" data-anchor-id="histograma-de-la-variable-performance_index">2. Histograma de la variable <em>performance_index</em></h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En el histograma, podemos apreciar que la variable <em>performance_index</em> sigue una distribución normal.</p>
<p>La línea roja marca la distribución, mientras que las líneas verdes discontinuas marcan los valores de los cuartiles; entre los que se encuentra el 50% de la muestra para esta variable.</p>
<p>Esto complementa a lo que hemos deducido previamente a partir de los datos de la media y la mediana.</p>
</section>
<section id="distribución-de-frecuencias-relativas" class="level2">
<h2 class="anchored" data-anchor-id="distribución-de-frecuencias-relativas">3. Distribución de frecuencias relativas</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Posición Frecuencia Frecuencia_Relativa
1   Defender        172               33.01
2    Forward        121               23.22
3 Goalkeeper         37                7.10
4 Midfielder        191               36.66</code></pre>
</div>
</div>
<p>Podemos observar que la frecuencia relativa de porteros es mucho menor que la del resto de posiciones. Esto se debe a que en un equipo juega un solo portero para los 3 o 4 defensas, 3 o 4 mediocentros y 2 o 3 delanteros. Por tanto, es lógico obtener ese valor. Caso análogo, pero en menor medida para los delanteros, que suponen un número inferior en la plantilla que los mediocentros y los defensas.</p>
</section>
<section id="diagrama-de-cajas-de-performace_index-según-el-equipo" class="level2">
<h2 class="anchored" data-anchor-id="diagrama-de-cajas-de-performace_index-según-el-equipo">4. Diagrama de cajas de <em>performace_index</em> según el equipo</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En este <em>boxplot</em> podemos ver que en el equipo B hay una mayor variabilidad de resultados, pues los cuartiles son más grandes que los de los equipos A y B (que tienen niveles más similares de rendimiento). Sin embargo, la mediana del equipo B es claramente mayor que la del resto de equipos.</p>
<p>Esto puede indicar un mayor nivel de algunos jugadores del equipo B con respecto de los jugadores del resto de equipos, pero también entre los jugadores del mismo equipo (mucha diferencia entre jugadores “estrellas” y el resto).</p>
<p>Por último, en el equipo C tienen todos los jugadores un nivel muy similar; lo que podría provocar que el rendimiento medio sea mayor.</p>
</section>
<section id="gráfico-de-dispersión-entre-training_hours-y-performance_index" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-de-dispersión-entre-training_hours-y-performance_index">5. Gráfico de dispersión entre <em>training_hours</em> y <em>performance_index</em></h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Se aprecia linealidad en el modelo. Hay una clara relación lineal entre las horas de entrenamiento y el índice de rendimiento, apreciando un mayor rendimiento conforme aumentan las horas de entrenamiento.</p>
</section>
<section id="matriz-de-correlaciones" class="level2">
<h2 class="anchored" data-anchor-id="matriz-de-correlaciones">6. Matriz de correlaciones</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  performance_index injuries_count      starter
performance_index        1.00000000    0.023092517  0.062093683
injuries_count           0.02309252    1.000000000 -0.012381095
starter                  0.06209368   -0.012381095  1.000000000
passes_attempted         0.03759048   -0.030800317 -0.059914133
passes_success           0.22380445   -0.023382065 -0.017004059
age                      0.50942713    0.045909025  0.034108003
training_hours           0.58645594    0.051006061  0.044900932
match_intensity          0.10552445   -0.026426679  0.081841376
sleep_hours              0.14023856    0.021746277  0.020135890
travel_km_week          -0.22917329   -0.007683223 -0.200966251
fatigue                 -0.23504795    0.079240490 -0.065515153
strength_1RM             0.02651421   -0.147472578  0.130241382
agility_time            -0.08322814   -0.106329647 -0.017235246
nutrition_score          0.02612729   -0.006310515 -0.016386628
left_footed              0.07554008   -0.013995969  0.026497015
previous_injuries        0.00814568    0.164320068 -0.009129866
altitude_home           -0.06560546    0.022619805  0.009302464
                  passes_attempted passes_success          age training_hours
performance_index      0.037590485    0.223804447  0.509427135    0.586455936
injuries_count        -0.030800317   -0.023382065  0.045909025    0.051006061
starter               -0.059914133   -0.017004059  0.034108003    0.044900932
passes_attempted       1.000000000    0.819494081 -0.056254340    0.038102814
passes_success         0.819494081    1.000000000 -0.014567435    0.213223626
age                   -0.056254340   -0.014567435  1.000000000   -0.020653352
training_hours         0.038102814    0.213223626 -0.020653352    1.000000000
match_intensity       -0.056004739    0.047746426 -0.002487031    0.024869382
sleep_hours            0.009511588   -0.009584384  0.057785490   -0.001016533
travel_km_week        -0.044569200   -0.095566982 -0.024826426   -0.103487984
fatigue               -0.064798747   -0.294289561 -0.022952080   -0.024781872
strength_1RM          -0.072304348    0.014368416  0.043252441    0.075065530
agility_time           0.065097072   -0.270118368 -0.075836548    0.009000297
nutrition_score       -0.017948243    0.068165128  0.061316510    0.015784391
left_footed           -0.002290794    0.010792863  0.001072423    0.054981161
previous_injuries     -0.059215842   -0.040318518  0.057127118    0.016374733
altitude_home          0.027052735   -0.012245360 -0.015085890   -0.048684328
                  match_intensity  sleep_hours travel_km_week      fatigue
performance_index     0.105524449  0.140238561   -0.229173294 -0.235047946
injuries_count       -0.026426679  0.021746277   -0.007683223  0.079240490
starter               0.081841376  0.020135890   -0.200966251 -0.065515153
passes_attempted     -0.056004739  0.009511588   -0.044569200 -0.064798747
passes_success        0.047746426 -0.009584384   -0.095566982 -0.294289561
age                  -0.002487031  0.057785490   -0.024826426 -0.022952080
training_hours        0.024869382 -0.001016533   -0.103487984 -0.024781872
match_intensity       1.000000000  0.065033506   -0.079693916 -0.030713438
sleep_hours           0.065033506  1.000000000   -0.085058788 -0.038366911
travel_km_week       -0.079693916 -0.085058788    1.000000000 -0.039727310
fatigue              -0.030713438 -0.038366911   -0.039727310  1.000000000
strength_1RM          0.034583244 -0.018360833    0.009829000  0.016890817
agility_time         -0.034191671  0.021689683    0.046511935 -0.004996277
nutrition_score      -0.005988961 -0.041943763    0.024525683  0.007531836
left_footed           0.018102343  0.031790171    0.048178595 -0.016531942
previous_injuries     0.031758637  0.084312165    0.060747566  0.017443859
altitude_home         0.034823093 -0.009805810    0.052403040  0.019959785
                   strength_1RM agility_time nutrition_score   left_footed
performance_index  0.0265142085 -0.083228135     0.026127294  0.0755400844
injuries_count    -0.1474725783 -0.106329647    -0.006310515 -0.0139959695
starter            0.1302413820 -0.017235246    -0.016386628  0.0264970150
passes_attempted  -0.0723043475  0.065097072    -0.017948243 -0.0022907939
passes_success     0.0143684158 -0.270118368     0.068165128  0.0107928629
age                0.0432524407 -0.075836548     0.061316510  0.0010724228
training_hours     0.0750655296  0.009000297     0.015784391  0.0549811607
match_intensity    0.0345832442 -0.034191671    -0.005988961  0.0181023434
sleep_hours       -0.0183608326  0.021689683    -0.041943763  0.0317901707
travel_km_week     0.0098290001  0.046511935     0.024525683  0.0481785948
fatigue            0.0168908167 -0.004996277     0.007531836 -0.0165319420
strength_1RM       1.0000000000 -0.060215946     0.015486838  0.0001416806
agility_time      -0.0602159457  1.000000000    -0.003290947  0.0361351170
nutrition_score    0.0154868382 -0.003290947     1.000000000  0.0406846996
left_footed        0.0001416806  0.036135117     0.040684700  1.0000000000
previous_injuries -0.0324557564  0.025610597     0.007514404 -0.0034503837
altitude_home      0.0809435042  0.016062592    -0.013897573 -0.0277691299
                  previous_injuries altitude_home
performance_index       0.008145680  -0.065605461
injuries_count          0.164320068   0.022619805
starter                -0.009129866   0.009302464
passes_attempted       -0.059215842   0.027052735
passes_success         -0.040318518  -0.012245360
age                     0.057127118  -0.015085890
training_hours          0.016374733  -0.048684328
match_intensity         0.031758637   0.034823093
sleep_hours             0.084312165  -0.009805810
travel_km_week          0.060747566   0.052403040
fatigue                 0.017443859   0.019959785
strength_1RM           -0.032455756   0.080943504
agility_time            0.025610597   0.016062592
nutrition_score         0.007514404  -0.013897573
left_footed            -0.003450384  -0.027769130
previous_injuries       1.000000000   0.059581765
altitude_home           0.059581765   1.000000000</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Aquí podemos ver la matriz de correlaciones. Vemos que las variables que presentan más correlación son los pases realizados con éxito y los pases intentados. Otras variables que presentan cierta correlación son el índice de rendimiento con la edad y las horas de entrenamiento.</p>
</section>
<section id="gráfico-de-dispersión-entre-fatiga-e-índice-de-rendimiento" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-de-dispersión-entre-fatiga-e-índice-de-rendimiento">7. Gráfico de dispersión entre fatiga e índice de rendimiento</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Parece que hay una relación lineal entre ambas variables. En particular, podemos observar que parece haber una relación que indica una menor índice de rendimiento conforme la fatiga incrementa.</p>
</section>
<section id="boxplot-del-índice-de-rendimiento-por-posición" class="level2">
<h2 class="anchored" data-anchor-id="boxplot-del-índice-de-rendimiento-por-posición">8. Boxplot del índice de rendimiento por posición</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Se aprecian una serie de diferencias entre puestos, que procederemos a desarrollar. En primer lugar, no hay grandes diferencias en lo referente a la media del índice de rendimiento en función de la posición. Por otro lado, vemos que el tercer cuartil de los defensas es más pequeño que el resto, dando a entender que se encuentran más agrupados en esas zonas de rendimiento; destacando menos que en otras posiciones. Además, hay tres outliers con valores muy bajos de rendimiento. Finalmente, el último valor remarcable es el del portero, donde vemos que el “bigote” es de longitud mucho menor que el del resto de posiciones.</p>
</section>
<section id="valores-atípicos-en-agility_time" class="level2">
<h2 class="anchored" data-anchor-id="valores-atípicos-en-agility_time">9. Valores atípicos en <em>agility_time</em></h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA NA NA NA NA</code></pre>
</div>
</div>
<p>Vemos que por la regla del rango intercuartílico (IQR) hay 5 valores atípicos, que se corresponden con NA. Es decir, valores no recogidos de esta variable para ciertos jugadores. Vamos a hacer un boxplot para intentar ver más posibles valores atípicos, donde estos hayan sido recogidos.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La conclusión del boxplot es la misma. No hay valores atípicos en la variable agility_time, más allá de los valores no recogidos.</p>
</section>
<section id="proporción-de-jugadores-zurdos-en-la-base-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="proporción-de-jugadores-zurdos-en-la-base-de-datos">10. Proporción de jugadores zurdos en la base de datos</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29.17466</code></pre>
</div>
</div>
<p>Como podemos ver, el 29,17% de los jugadores de la base de datos son zurdos.</p>
</section>
</section>
<section id="manejo-de-valores-faltantes" class="level1">
<h1>2. MANEJO DE VALORES FALTANTES</h1>
<section id="identificación-de-variables-con-valores-faltantes" class="level2">
<h2 class="anchored" data-anchor-id="identificación-de-variables-con-valores-faltantes">1. Identificación de variables con valores faltantes</h2>
<p>Primero, vemos qué columnas tienen valores NA</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "training_hours" "sleep_hours"    "fatigue"        "strength_1RM"  
[5] "agility_time"  </code></pre>
</div>
</div>
<p>Las variables <em>training_hours</em>, <em>sleep_hours</em>, <em>fatigue</em>, <em>strength_1RM</em> y <em>agility_time</em> tienen valores faltantes.</p>
<p>Ahora, veremos cuántos valores faltan en cada una</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>training_hours    sleep_hours        fatigue   strength_1RM   agility_time 
             5              5              5              5              5 </code></pre>
</div>
</div>
<p>Así, vemos que hay 5 valores faltantes en cada una de estas variables.</p>
</section>
<section id="calculamos-la-proporción-de-valores-faltantes-sobre-el-dataset-completo" class="level2">
<h2 class="anchored" data-anchor-id="calculamos-la-proporción-de-valores-faltantes-sobre-el-dataset-completo">2. Calculamos la proporción de valores faltantes sobre el dataset completo</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2525508</code></pre>
</div>
</div>
<p>Es decir, el 0.25% de los valores del dataset son valores faltantes.</p>
</section>
<section id="resumen-de-combina-las-variables-con-missing-y-su-porcentaje-de-valores-ausentes" class="level2">
<h2 class="anchored" data-anchor-id="resumen-de-combina-las-variables-con-missing-y-su-porcentaje-de-valores-ausentes">3. Resumen de combina las variables con missing y su porcentaje de valores ausentes</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                     variable na_count na_percent
training_hours training_hours        5  0.0403071
sleep_hours       sleep_hours        5  0.0403071
fatigue               fatigue        5  0.0403071
strength_1RM     strength_1RM        5  0.0403071
agility_time     agility_time        5  0.0403071</code></pre>
</div>
</div>
</section>
<section id="imputación-por-la-media-en-training_hours" class="level2">
<h2 class="anchored" data-anchor-id="imputación-por-la-media-en-training_hours">4. Imputación por la media en <em>training_hours</em></h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.69029</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.69029</code></pre>
</div>
</div>
<p>Con esto, hemos sustituido los valores faltantes de la variable <em>training_hours</em> con la media de los valores de esta variable.</p>
</section>
<section id="histogramas-de-sleep_hours-antes-y-después-de-la-imputación-por-la-media" class="level2">
<h2 class="anchored" data-anchor-id="histogramas-de-sleep_hours-antes-y-después-de-la-imputación-por-la-media">5. Histogramas de <em>sleep_hours</em> antes y después de la imputación por la media</h2>
<p>En primer lugar, trabajaremos con la variable sin imputar (con valores faltantes).</p>
<p>A continuación, trabajaremos con la versión imputada.</p>
<p>Ahora, podemos desarrollar los histogramas.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como podemos ver, no se aprecian diferencias aparentes. Esto se debe al hecho de que, al imputar los valores faltantes por la media, no modificamos la estructura presente de la variable. Así, el único cambio aparente es un aumento de la frecuencia para los valores cercanos a la mediana (asumimos que son los imputados). Sin embargo, como afirmamos, la distribución es la misma.</p>
</section>
<section id="imputación-por-la-mediana-en-fatigue-y-comparación-con-imputación-con-la-media." class="level2">
<h2 class="anchored" data-anchor-id="imputación-por-la-mediana-en-fatigue-y-comparación-con-imputación-con-la-media.">6. Imputación por la mediana en <em>fatigue</em> y comparación con imputación con la media.</h2>
<p>En primer lugar, imputamos los valores por la mediana en la variable <em>fatigue</em>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>A continuación, hacemos la imputación por la media.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Ahora, porcedemos a comparar estas nuevas variables creadas.</p>
<p>Para ello, empezaremos comparando estadísticas básicas mediante una tabla</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             Version    Media Mediana
1           Original 49.40407    49.3
2 Imputación Mediana 49.40307    49.3
3   Imputación Media 49.40407    49.3</code></pre>
</div>
</div>
<p>De esta manera, vemos que la imputación por la mediana modifica ligeramente la media de la variable; mientras que el valor de la mediana permanece intacto en cualquier caso.</p>
<p>Vamos a ver si este cambio es significativo. Para ello, haremos un <em>t-test</em>, cuya hipótesis nula será que el cambio no es significativo.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  original and imputada_mediana[1:length(original)]
t = 0.11774, df = 515, p-value = 0.9063
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -1.544242  1.741141
sample estimates:
mean difference 
     0.09844961 </code></pre>
</div>
</div>
<p>El p-valor resulta muy elevado, por lo que no podemos rechazar la hipótesis nula. De esta manera, concluimos que la diferencia no es estadísticamente significativa.</p>
<p>A continuación, haremos una comparación de histogramas, para ver si a nivel visual hay una diferencia apreciable.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como se puede ver, a nivel visual apenas hay diferencia. Simplemente, en ambas imputaciones,la barra que abarca los valores de la mediana incrementa (ya que la media es próxima a la mediana), pero mantienen la estructura.</p>
<p>Así, concluimos que apenas hay diferencias entre ambas imputaciones.</p>
</section>
<section id="imputación-condicional-en-strength_1rm" class="level2">
<h2 class="anchored" data-anchor-id="imputación-condicional-en-strength_1rm">7. Imputación condicional en <em>strength_1RM</em></h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Una vez creada la variable, verificamos que cumple los objetivos y actualizaremos la variable <em>strength_1RM</em> del conjunto de datos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  position   media_strength
  &lt;chr&gt;               &lt;dbl&gt;
1 Defender             147.
2 Forward              148.
3 Goalkeeper           154.
4 Midfielder           151.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  position   media_strength
  &lt;chr&gt;               &lt;dbl&gt;
1 Defender             147.
2 Forward              148.
3 Goalkeeper           154.
4 Midfielder           151.</code></pre>
</div>
</div>
<p>Vemos que los valores coinciden, por lo que la imputación ha sido realizada de forma correcta.</p>
</section>
<section id="comentario-acerca-de-los-valores-faltantes" class="level2">
<h2 class="anchored" data-anchor-id="comentario-acerca-de-los-valores-faltantes">8. Comentario acerca de los valores faltantes</h2>
<p>En primer lugar, para ello, vamos a ver el patrón de los NA. Es decir, vamos a ver dónde aparecen los NA, si hay combinaciones de NA entre variables o si aparecen de forma aleatoria.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    performance_index injuries_count starter passes_attempted passes_success
496                 1              1       1                1              1
5                   1              1       1                1              1
5                   1              1       1                1              1
5                   1              1       1                1              1
5                   1              1       1                1              1
5                   1              1       1                1              1
                    0              0       0                0              0
    age match_intensity position travel_km_week nutrition_score team
496   1               1        1              1               1    1
5     1               1        1              1               1    1
5     1               1        1              1               1    1
5     1               1        1              1               1    1
5     1               1        1              1               1    1
5     1               1        1              1               1    1
      0               0        0              0               0    0
    left_footed previous_injuries altitude_home training_hours sleep_hours
496           1                 1             1              1           1
5             1                 1             1              1           1
5             1                 1             1              1           1
5             1                 1             1              1           1
5             1                 1             1              1           0
5             1                 1             1              0           1
              0                 0             0              5           5
    fatigue strength_1RM agility_time   
496       1            1            1  0
5         1            1            0  1
5         1            0            1  1
5         0            1            1  1
5         1            1            1  1
5         1            1            1  1
          5            5            5 25</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-29-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como podemos apreciar, no hay NA agrupados en la misma observación. Por tanto, podemos intuir que los valores faltantes son fruto del azar (MCAR). Por tanto, nos ayudaremos de un test estadístico que nos diga si lo son (el test mcar).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-30-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  statistic    df p.value missing.patterns
      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;            &lt;int&gt;
1      109.    90  0.0800                6</code></pre>
</div>
</div>
<p>Como el p-valor es mayor de 0.05, no podemos rechazar que sean MCAR.</p>
<p>Con esto y la información anterior, podemos concluir que los valores faltantes que tenemos son MCAR, al provenir completamente del azar.</p>
</section>
<section id="modelo-lineal-simple-entre-performance_index-y-training_hours" class="level2">
<h2 class="anchored" data-anchor-id="modelo-lineal-simple-entre-performance_index-y-training_hours">9. Modelo lineal simple entre <em>performance_index</em> y <em>training_hours</em></h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours, data = datos, 
    na.action = na.omit)

Residuals:
     Min       1Q   Median       3Q      Max 
-24.1764  -5.2639   0.5892   5.9276  23.4731 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     35.9086     1.4874   24.14   &lt;2e-16 ***
training_hours   1.7112     0.1056   16.20   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.888 on 514 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.3379,    Adjusted R-squared:  0.3367 
F-statistic: 262.4 on 1 and 514 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Como tenemos un modelo con 514 grados de libertad, es fácil deducir que se han perdido 5 observaciones por NA.</p>
<p>A continuación, vamos a ver qué filas se han perdido exactamente.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 109 131 180 393 500</code></pre>
</div>
</div>
</section>
<section id="modelo-lineal-con-valores-imputados" class="level2">
<h2 class="anchored" data-anchor-id="modelo-lineal-con-valores-imputados">10. Modelo lineal con valores imputados</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = datos$performance_index ~ training_hours_imputada)

Residuals:
     Min       1Q   Median       3Q      Max 
-26.3421  -5.2274   0.5909   6.0180  23.5766 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              35.8050     1.5136   23.66   &lt;2e-16 ***
training_hours_imputada   1.7112     0.1075   15.91   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.029 on 519 degrees of freedom
Multiple R-squared:  0.3279,    Adjusted R-squared:  0.3266 
F-statistic: 253.2 on 1 and 519 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Vemos la diferencia entre los coeficientes de los modelos</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) training_hours 
     35.908593       1.711218 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            (Intercept) training_hours_imputada 
              35.805026                1.711218 </code></pre>
</div>
</div>
<p>Los coeficientes han cambiado ligeramente, al cambiar el número de observaciones, con valores añadidos manualmente. Sin embargo, la diferencia es mínima, al haber muy pocos valores faltantes, por lo que los cambios no influyen prácticamente en el modelo; ya que los coeficientes cambian mínimamente.</p>
</section>
</section>
<section id="regresión-lineal-simple-y-múltiple" class="level1">
<h1>3. REGRESIÓN LINEAL SIMPLE Y MÚLTIPLE</h1>
<section id="modelo-de-regresión-lineal-simple-entre-performance_index-y-training_hours" class="level2">
<h2 class="anchored" data-anchor-id="modelo-de-regresión-lineal-simple-entre-performance_index-y-training_hours">1. Modelo de regresión lineal simple entre <em>performance_index</em> y <em>training_hours</em></h2>
<p>Emplearemos las variables imputadas comentadas previamente.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = datos$performance_index ~ training_hours_imputada)

Residuals:
     Min       1Q   Median       3Q      Max 
-26.3421  -5.2274   0.5909   6.0180  23.5766 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              35.8050     1.5136   23.66   &lt;2e-16 ***
training_hours_imputada   1.7112     0.1075   15.91   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.029 on 519 degrees of freedom
Multiple R-squared:  0.3279,    Adjusted R-squared:  0.3266 
F-statistic: 253.2 on 1 and 519 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>La pendiente (con valor 1.7112) indica que, por cada hora de entrenamiento, el valor del índice de rendimiento aumenta 1.7112.</p>
</section>
<section id="gráfico-de-dispersión-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-de-dispersión-del-modelo">2. Gráfico de dispersión del modelo</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="cálculo-y-análisis-del-r2-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="cálculo-y-análisis-del-r2-del-modelo">3. Cálculo y análisis del R^2 del modelo</h2>
<p>En primer lugar, calcularemos el R^2 del modelo.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3279338</code></pre>
</div>
</div>
<p>El R^2 vale 0.3279338. Esto quiere decir que el modelo explica un 32.79% de la variabilidad del índice de rendimiento.</p>
</section>
<section id="modelo-de-regresión-lineal-múltiple" class="level2">
<h2 class="anchored" data-anchor-id="modelo-de-regresión-lineal-múltiple">4. Modelo de regresión lineal múltiple</h2>
<p>Vamos a ajustar un modelo de regresión lineal múltiple con la variable <em>performance_index</em> explicada a partir de <em>training_hours</em>, <em>match_intensity</em> y <em>strength_1RM</em>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours + match_intensity + 
    strength_1RM, data = datos, na.action = na.omit)

Residuals:
     Min       1Q   Median       3Q      Max 
-23.5439  -5.0539   0.4122   5.9659  23.2461 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     31.79396    3.30520   9.619   &lt;2e-16 ***
training_hours   1.72530    0.10617  16.250   &lt;2e-16 ***
match_intensity  0.07622    0.03036   2.510   0.0124 *  
strength_1RM    -0.01003    0.01497  -0.670   0.5031    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.859 on 507 degrees of freedom
  (10 observations deleted due to missingness)
Multiple R-squared:  0.3494,    Adjusted R-squared:  0.3455 
F-statistic: 90.76 on 3 and 507 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>La variable que más efecto tiene sobre el rendimiento es <em>training_hours</em>, cuyo coeficiente asociado vale 1.7253 (mucho mayor que el valor absoluto del resto).</p>
</section>
<section id="comparación-con-el-modelo-simple" class="level2">
<h2 class="anchored" data-anchor-id="comparación-con-el-modelo-simple">5. Comparación con el modelo simple</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>training_hours 
      1.711218 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>training_hours 
      1.725297 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   35.90859 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   31.79396 </code></pre>
</div>
</div>
<p>Vemos, de esta manera, que el coeficiente de la variable <em>training_hours</em> aumenta en el modelo múltiple y el intercepto disminuye su valor.</p>
<p>Esto se debe a que los coeficientes asociados a las otras variables le restan valor a las horas de entrenamientos, ajustándose así a la realidad que permite explicar el modelo. Por otro lado, tiene sentido que el intercepto sea menor, ya que la pendiente parece más pronunciada por este incremento del coeficiente asociado a la variable <em>training_hours</em>.</p>
</section>
<section id="adición-de-la-variable-fatigue" class="level2">
<h2 class="anchored" data-anchor-id="adición-de-la-variable-fatigue">6. Adición de la variable <em>fatigue</em></h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours + match_intensity + 
    strength_1RM + fatigue, data = datos, na.action = na.omit)

Residuals:
     Min       1Q   Median       3Q      Max 
-23.2689  -4.9222   0.5522   5.5810  20.8094 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     39.402280   3.411640  11.549  &lt; 2e-16 ***
training_hours   1.707699   0.102800  16.612  &lt; 2e-16 ***
match_intensity  0.070766   0.029355   2.411   0.0163 *  
strength_1RM    -0.007318   0.014491  -0.505   0.6138    
fatigue         -0.149997   0.023112  -6.490 2.07e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.583 on 501 degrees of freedom
  (15 observations deleted due to missingness)
Multiple R-squared:  0.3996,    Adjusted R-squared:  0.3948 
F-statistic: 83.36 on 4 and 501 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El R^2 ajustado ha mejorado tras añadir esta nueva variable al modelo. Esto significa que es útil, ya que el hecho de haberla añadido permite explicar cierta variabilidad del índice de rendimiento.</p>
</section>
<section id="efecto-de-la-variable-position" class="level2">
<h2 class="anchored" data-anchor-id="efecto-de-la-variable-position">7. Efecto de la variable <em>position</em></h2>
<p>Si metemos la variable categórica <em>position</em> en un modelo de regresión lineal múltiple con predictores cuantitativos, la variable categórica se convierte en valores Dummy de la siguiente manera:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    position positionforward positiongoalkeeper positionmidfielder
1    forward               1                  0                  0
2   defender               0                  0                  0
4 midfielder               0                  0                  1
9 goalkeeper               0                  1                  0</code></pre>
</div>
</div>
<p>En este caso, se habrían estimado estos coeficientes Dummy para las posiciones.</p>
<p>El que tiene todo 0 es la referencia (en este caso, los defensas). El resto de coeficientes Dummy se comparan con este nivel.</p>
<p>El modelo devolverá un valor entre la diferencia de posiciones, que permite determinar la diferencia de rendimiento entre jugadores de las mismas.</p>
</section>
<section id="incluimos-sleep_hours-como-predictor-adicional" class="level2">
<h2 class="anchored" data-anchor-id="incluimos-sleep_hours-como-predictor-adicional">8. Incluimos <em>sleep_hours</em> como predictor adicional</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours + match_intensity + 
    strength_1RM + fatigue + sleep_hours, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-23.4997  -5.0862   0.6675   5.3974  24.1631 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     29.884450   4.271003   6.997 8.53e-12 ***
training_hours   1.698145   0.101610  16.712  &lt; 2e-16 ***
match_intensity  0.064253   0.029056   2.211 0.027466 *  
strength_1RM    -0.006181   0.014306  -0.432 0.665898    
fatigue         -0.144825   0.022863  -6.334 5.36e-10 ***
sleep_hours      1.351032   0.367915   3.672 0.000267 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.456 on 495 degrees of freedom
  (20 observations deleted due to missingness)
Multiple R-squared:  0.4143,    Adjusted R-squared:  0.4084 
F-statistic: 70.02 on 5 and 495 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Con esto, podemos ver que la fatiga influye negativamente en el rendimiento de los jugadores. De esta manera, el descanso será necesario para obtener un buen rendimiento.</p>
</section>
<section id="diagrama-de-residuos-del-modelo-múltiple" class="level2">
<h2 class="anchored" data-anchor-id="diagrama-de-residuos-del-modelo-múltiple">9. Diagrama de residuos del modelo múltiple</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los puntos aparecen dispersos aparentemente al azar en torno a la línea central. Este es un indicio de linealidad, por lo que no hay ningún motivo aparente como para descartarla. Es verdad que hay un ligero indicio de curva, pero no lo suficiente como para tomar la conclusión de descartar la linealidad.</p>
</section>
<section id="modelo-lineal-simple-vs-múltiple" class="level2">
<h2 class="anchored" data-anchor-id="modelo-lineal-simple-vs-múltiple">10. Modelo lineal simple vs múltiple</h2>
<p>Para este dataset, conviene más utilizar un modelo lineal simple cuando se quiere ver de forma “pura” el efecto de una sola variable para el explicar el rendimiento o cualquier otra variable. Sin embargo, si queremos explicar el por qué de una variable o de su distribución, esto no se va a deber solo a un predictor, sino que habrá que tomar varios que lo expliquen.</p>
<p>De esta manera, nos conviene usar un modelo simple para ver cómo influye una variable en las demás, pero nos conviene usar un modelo múltiple para entender el comportamiento real de una variable a partir de las demás (y que se recoja mejor toda su variabilidad, atendiendo a todos sus posibles condicionantes que la alteren).</p>
</section>
</section>
<section id="no-linealidades-y-piecewise" class="level1">
<h1>4. NO LINEALIDADES Y PIECEWISE</h1>
<section id="modelo-no-lineal" class="level2">
<h2 class="anchored" data-anchor-id="modelo-no-lineal">1. Modelo no lineal</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-24.1764  -5.2639   0.5892   5.9276  23.4731 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     35.9086     1.4874   24.14   &lt;2e-16 ***
training_hours   1.7112     0.1056   16.20   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.888 on 514 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.3379,    Adjusted R-squared:  0.3367 
F-statistic: 262.4 on 1 and 514 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours + I(training_hours^2), 
    data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-23.2383  -5.1859   0.5024   5.8237  22.6082 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         21.42297    4.26137   5.027 6.89e-07 ***
training_hours       3.93294    0.62228   6.320 5.68e-10 ***
I(training_hours^2) -0.08036    0.02219  -3.622 0.000322 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.797 on 513 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.3544,    Adjusted R-squared:  0.3519 
F-statistic: 140.8 on 2 and 513 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>A continuación, compararemos los modelos con ANOVA, con R^2 ajustado y con AIC</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: performance_index ~ training_hours
Model 2: performance_index ~ training_hours + I(training_hours^2)
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1    514 31981                                  
2    513 31183  1     797.3 13.116 0.0003218 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Vemos que el p-valor del test es bastante menor que 0.05, lo cual indica que el modelo cuadrático es mejor, ya que explica mejor la varianza en el modelo.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3366563</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.351933</code></pre>
</div>
</div>
<p>Vemos que el R^2 del modelo cuadrático es mayor que el del modelo lineal, por lo que hay más porcentaje de variabilidad explicada de la variable <em>performance_index</em> en el modelo cuadrátrico.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                           df      AIC
modelo_lineal_training      3 3599.765
modelo_cuadratico_training  4 3588.738</code></pre>
</div>
</div>
<p>Vemos que en el modelo cuadrático hay un valor menor de AIC. Esto implica que será un mejor modelo, logrando un mejor ajuste que el modelo lineal sin añadir excesiva complejidad.</p>
<p>Con todo esto, podemos concluir que el modelo cuadrático es notablemente mejor que el modelo lineal.</p>
</section>
<section id="relación-entre-performance_index-y-age" class="level2">
<h2 class="anchored" data-anchor-id="relación-entre-performance_index-y-age">2. Relación entre <em>performance_index</em> y <em>age</em></h2>
<p>En primer lugar, haremos un gráfico de dispersión para ver la relación</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Esto nos permite intuir que el índice de rendimiento parece ser mayor conforme la edad aumenta. Sin embargo, para verificarlo y detectar formas cuadráticas, haremos un modelo cuadrático.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ age + I(age^2), data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-26.0040  -5.3093   0.5897   6.0090  18.5583 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -21.41722    8.25487  -2.594  0.00974 ** 
age           5.40080    0.63705   8.478 2.40e-16 ***
I(age^2)     -0.08492    0.01186  -7.161 2.76e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.071 on 518 degrees of freedom
Multiple R-squared:  0.3222,    Adjusted R-squared:  0.3195 
F-statistic: 123.1 on 2 and 518 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Efectivamente, tal y como intuíamos, el índice de rendimiento incrementa conforme la edad aumenta.</p>
<p>Además, vemos que <em>age^2</em> es negativo en el modelo. Con esto, sabemos que obtendremos un pico en el modelo. Para verlo mejor, añadiremos al gráfico anterior la curva del modelo cuadrático.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Así, la relación es cuadrática, aunque parece tener una tendencia suave; no muy pronunciada. Vamos a calcular el valor del pico y lo añadiremos a la gráfica anterior.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     age 
31.80029 </code></pre>
</div>
</div>
<p>Así, el pico de rendimiento se da a los 31.80029 años. A partir de entonces, el rendimiento empieza a bajar. A continuación aparece el gráfico completo con el pico marcado.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="variable-dicotómica-para-sleep_hours" class="level2">
<h2 class="anchored" data-anchor-id="variable-dicotómica-para-sleep_hours">3. Variable dicotómica para <em>sleep_hours</em></h2>
<p>Una vez creada la variable, la ajustaremos como predictora del modelo</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ sleep_group, data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-32.287  -6.160   0.823   7.130  25.499 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      57.121      1.322  43.214   &lt;2e-16 ***
sleep_group≥6h    2.436      1.397   1.744   0.0818 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.713 on 514 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.005881,  Adjusted R-squared:  0.003947 
F-statistic: 3.041 on 1 and 514 DF,  p-value: 0.08179</code></pre>
</div>
</div>
<p>Analizando la salida, vemos que los jugadores que han dormido más de 6 horas incrementan su rendimiento. El intercepto indica la media de rendimiento de jugadores con menos de 6 horas de sueño, mientras que el otro coeficiente (2.436) indica la diferencia entre los jugadores que han dormido más de 6 horas con respecto de aquellos que no. De esta manera, un mayor descanso deriva en un mejor rendimiento.</p>
<p>Por último, vamos a plantear un boxplot para visualizar mejor esta diferencia.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="performance_index-frente-a-fatigue-empleando-un-loess" class="level2">
<h2 class="anchored" data-anchor-id="performance_index-frente-a-fatigue-empleando-un-loess">4. <em>performance_index</em> frente a <em>fatigue</em> empleando un LOESS</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Podemos ver en la gráfica que la relación planteada es no lineal, con dos pequeños “picos” y un “valle” entre medias, y una posterior caída.</p>
</section>
<section id="spline-sobre-training_hours-y-comparación-con-método-cuadrático" class="level2">
<h2 class="anchored" data-anchor-id="spline-sobre-training_hours-y-comparación-con-método-cuadrático">5. Spline sobre <em>training_hours</em> y comparación con método cuadrático</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ bs(training_hours, df = 4), 
    data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-22.703  -5.074   0.777   5.754  22.088 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  41.7839     4.0072  10.427  &lt; 2e-16 ***
bs(training_hours, df = 4)1   0.8347     5.8272   0.143    0.886    
bs(training_hours, df = 4)2  27.9440     3.9598   7.057 5.57e-12 ***
bs(training_hours, df = 4)3  22.9482     5.8135   3.947 9.01e-05 ***
bs(training_hours, df = 4)4  32.5914     6.2000   5.257 2.16e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.785 on 511 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.3588,    Adjusted R-squared:  0.3538 
F-statistic: 71.49 on 4 and 511 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>A continuación, graficaremos ambos modelos para ver la diferencia</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vemos que el spline recoge mejor la no linealidad de la relación, ajustándose mejor a los valores reales.</p>
<p>Por otro lado, vamos a comparar formalmente ambos ajustes.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                           df      AIC
modelo_cuadratico_training  4 3588.738
modelo_spline               6 3589.228</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.351933</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.353806</code></pre>
</div>
</div>
<p>Vemos que el AIC del modelo cuadrático es algo mayor, por lo que se ajusta un poco mejor a la relación. Sin embargo, el R^2 del modelo spline es mayor, explicando más variabilidad.</p>
<p>La conclusión que podemos sacar es que ambos modelos son muy similares, explicando una variabilidad parecida. De esta manera, no parece que uno sea mucho mejor que el otro.</p>
</section>
<section id="piecewise-en-travel_km_week" class="level2">
<h2 class="anchored" data-anchor-id="piecewise-en-travel_km_week">6. Piecewise en travel_km_week</h2>
<p>En primer lugar, vamos a crear la variable dicotómica <em>travel_group</em>.</p>
<p>A continuación, ajustaremos el modelo lineal con esta variable.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ travel_group, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-29.1315  -5.8417   0.4485   7.1985  22.7085 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        59.9115     0.4469 134.049  &lt; 2e-16 ***
travel_group&gt;1500  -5.9998     1.3281  -4.518 7.75e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.607 on 519 degrees of freedom
Multiple R-squared:  0.03783,   Adjusted R-squared:  0.03598 
F-statistic: 20.41 on 1 and 519 DF,  p-value: 7.753e-06</code></pre>
</div>
</div>
<p>Con la salida del modelo, vemos que el índice de rendimiento disminuye para aquellos jugadores que han viajado más de 1500 km a la semana. Esto se puede comprobar ya que el coeficiente asociado a esta variable es negativo (-5.9998). El valor de este coeficiente será la diferencia con los jugadores pertenecientes al otro grupo.</p>
<p>Finalmente, dispondremos un boxplot para ver la diferencia de manera visual.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="evaluación-del-aic-entre-modelos-lineal-cuadrático-y-piecewise-para-training_hours" class="level2">
<h2 class="anchored" data-anchor-id="evaluación-del-aic-entre-modelos-lineal-cuadrático-y-piecewise-para-training_hours">7. Evaluación del AIC entre modelos lineal, cuadrático y piecewise para <em>training_hours</em></h2>
<p>Tenemos el modelo lineal y el cuadrático creados en anteriores apartados. Nos falta, por tanto, crear el modelo piecewise.</p>
<p>Para ello, en primer lugar crearemos la variable dicotómica <em>training_group</em>.</p>
<p>Con esta, creamos el modelo piecewise</p>
<p>Ahora, podremos comparar el AIC de estos modelos</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                           df      AIC
modelo_lineal_training      3 3599.765
modelo_cuadratico_training  4 3588.738
modelo_piecewise_training   3 3784.518</code></pre>
</div>
</div>
<p>El modelo piecewise es el de mayor AIC, mientras que el cuadrático es el de menor AIC. De esta manera, el mejor modelo será el cuadrático, ya que es el que mejor combina ajuste y simplicidad.</p>
</section>
<section id="representación-gráfica-de-las-predicciones-del-modelo-piecewise-frente-a-las-observaciones-reales" class="level2">
<h2 class="anchored" data-anchor-id="representación-gráfica-de-las-predicciones-del-modelo-piecewise-frente-a-las-observaciones-reales">8. Representación gráfica de las predicciones del modelo piecewise frente a las observaciones reales</h2>
<p>En primer lugar, hacemos una predicción a partir del modelo piecewise</p>
<p>A continuación, hacemos la gráfica que permita ver la diferencia de esto frente a las observaciones reales.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>De esta manera, podemos ver las predicciones del modelo piecewise sobre las observaciones reales.</p>
</section>
<section id="ajuste-de-modelo-lineal-simple-con-casos-completos" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-de-modelo-lineal-simple-con-casos-completos">9. Ajuste de modelo lineal simple con casos completos</h2>
<p>En primer lugar, vamos a ver cuántos casos perdemos por quedarnos solo con los completos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 521</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 516</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>Vemos que perdemos 5 casos por valores faltantes.</p>
<p>A continuación, elaboramos el modelo´</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours, data = datos_completos)

Residuals:
     Min       1Q   Median       3Q      Max 
-24.1764  -5.2639   0.5892   5.9276  23.4731 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     35.9086     1.4874   24.14   &lt;2e-16 ***
training_hours   1.7112     0.1056   16.20   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.888 on 514 degrees of freedom
Multiple R-squared:  0.3379,    Adjusted R-squared:  0.3367 
F-statistic: 262.4 on 1 and 514 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="modelo-con-dataset-imputado" class="level2">
<h2 class="anchored" data-anchor-id="modelo-con-dataset-imputado">10. Modelo con dataset imputado</h2>
<p>Vamos a crear un dataset con todos los datos imputados</p>
<p>Ahora, planteamos el modelo con el nuevo dataset</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours, data = datos_imputados)

Residuals:
     Min       1Q   Median       3Q      Max 
-26.3421  -5.2274   0.5909   6.0180  23.5766 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     35.8050     1.5136   23.66   &lt;2e-16 ***
training_hours   1.7112     0.1075   15.91   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.029 on 519 degrees of freedom
Multiple R-squared:  0.3279,    Adjusted R-squared:  0.3266 
F-statistic: 253.2 on 1 and 519 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Cambia mínimamente el intercepto, pero es un cambio demasiado pequeño como para tenerlo en cuenta. Por otro lado, la pendiente sigue igual.</p>
</section>
</section>
<section id="heterocedasticidad" class="level1">
<h1>5. HETEROCEDASTICIDAD</h1>
<section id="ajuste-de-modelo-múltiple-con-gráfico-de-residuos" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-de-modelo-múltiple-con-gráfico-de-residuos">1. Ajuste de modelo múltiple con gráfico de residuos</h2>
<p>Vamos a crear el modelo múltiple con los datos imputados.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours + match_intensity + 
    strength_1RM + fatigue, data = datos_imputados)

Residuals:
     Min       1Q   Median       3Q      Max 
-25.6087  -4.7389   0.7036   5.5799  20.9780 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     39.519264   3.441646  11.483  &lt; 2e-16 ***
training_hours   1.694475   0.103973  16.297  &lt; 2e-16 ***
match_intensity  0.062419   0.029617   2.108   0.0356 *  
strength_1RM    -0.005358   0.014684  -0.365   0.7154    
fatigue         -0.143776   0.023417  -6.140 1.65e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.735 on 516 degrees of freedom
Multiple R-squared:  0.3798,    Adjusted R-squared:  0.375 
F-statistic: 79.01 on 4 and 516 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>A continuación, vamos a disponer el gráfico de residuos vs valores ajustados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-73-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En el gráfico podemos apreciar los residuos dispersos alrededor de 0 sin patrones aparentes, por lo que la relación lineal es razonable. Puede haber algo de heterocedasticidad, pero nada preocupante a priori.</p>
</section>
<section id="test-de-breusch-pagan" class="level2">
<h2 class="anchored" data-anchor-id="test-de-breusch-pagan">2. Test de Breusch-Pagan</h2>
<p>Aplicaremos al modelo recientemente creado el test mencionado para determinar si hay un problema de heterocedasticidad.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  modelo_multiple5.1
BP = 1.3407, df = 4, p-value = 0.8544</code></pre>
</div>
</div>
<p>El p-valor del test es muy elevado, por lo que no podemos rechazar la hipótesis de homocedasticidad. De esta manera, no podemos concluir que haya un problema de heterocedasticidad en el modelo.</p>
</section>
<section id="varianza-de-los-residuos-en-la-variable-fatigue" class="level2">
<h2 class="anchored" data-anchor-id="varianza-de-los-residuos-en-la-variable-fatigue">3. Varianza de los residuos en la variable <em>fatigue</em></h2>
<p>Empezaremos extrayendo los residuos del modelo, dividiendo los casos en 3 niveles de fatiga (bajo, medio y alto) dividiendo la muestra en terciles para tomar grupos con el mismo número de muestras.</p>
<p>A continuación, calculamos la varianza de los residuos en cada uno de los grupos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Bajo    Medio     Alto 
56.22624 58.08400 62.19390 </code></pre>
</div>
</div>
<p>Vemos que las varianzas son similares, pero con ligeras variaciones. Sin embargo, vamos a concluir si la diferencia entre estas es estadísticamente significativa. Para ello, usaremos el test de Bartlett.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  residuos by datos_imputados$fatigue_grupo
Bartlett's K-squared = 0.45836, df = 2, p-value = 0.7952</code></pre>
</div>
</div>
<p>Como el p-valor es muy elevado, no podemos afirmar que la diferencia de varianzas entre los residuos sea estadísticamente significativa.</p>
</section>
<section id="gráfica-de-residuos-vs-sleep_hours" class="level2">
<h2 class="anchored" data-anchor-id="gráfica-de-residuos-vs-sleep_hours">4. Gráfica de residuos vs <em>sleep_hours</em></h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-78-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En este caso, vemos como los residuos se alejan del 0, por lo que podemos detectar un ligero problema de heterocedasticidad; ya que la varianza de los residuos parece incrementar conforme lo hacen las horas de sueño.</p>
<p>De esta manera, podemos intuir que la varianza depende de las horas de sueño.</p>
</section>
<section id="modelo-con-errores-estándar-robusto-hc" class="level2">
<h2 class="anchored" data-anchor-id="modelo-con-errores-estándar-robusto-hc">5. Modelo con errores estándar robusto (HC)</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                    Coeficiente SE_Clasico SE_Robusto_HC3 Aumento_relativo
(Intercept)         (Intercept) 3.44164634     3.32179793        0.9651770
training_hours   training_hours 0.10397307     0.10224519        0.9833815
match_intensity match_intensity 0.02961712     0.02998461        1.0124080
strength_1RM       strength_1RM 0.01468369     0.01422877        0.9690190
fatigue                 fatigue 0.02341729     0.02352864        1.0047547</code></pre>
</div>
</div>
<p>Vemos que los errores de los coeficientes cambian considerablemente con respecto de los del modelo original.</p>
</section>
<section id="transformación-logarítmica-al-predictor-travel_km_week" class="level2">
<h2 class="anchored" data-anchor-id="transformación-logarítmica-al-predictor-travel_km_week">6. Transformación logarítmica al predictor <em>travel_km_week</em></h2>
<p>En primer lugar, creamos la variable transformada (le sumamos 1 para que no haya valores iguales a 0 y pueda tomar logaritmos).</p>
<p>A continuación, vamos a hacer el modelo con la variable ajustada</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours + match_intensity + 
    strength_1RM + fatigue + log_travel_km_week, data = datos_imputados)

Residuals:
     Min       1Q   Median       3Q      Max 
-25.2785  -4.6013   0.7295   5.5420  21.2503 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        41.494450   3.626785  11.441  &lt; 2e-16 ***
training_hours      1.686074   0.103901  16.228  &lt; 2e-16 ***
match_intensity     0.058404   0.029657   1.969   0.0495 *  
strength_1RM       -0.004876   0.014660  -0.333   0.7396    
fatigue            -0.144569   0.023379  -6.184 1.28e-09 ***
log_travel_km_week -0.271818   0.160001  -1.699   0.0900 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.721 on 515 degrees of freedom
Multiple R-squared:  0.3833,    Adjusted R-squared:  0.3773 
F-statistic: 64.01 on 5 and 515 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Para ver si mejora la heterocedasticidad dibujaremos la gráfica de residuos vs valores ajustados de este nuevo modelo</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-82-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-82-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La gráfica es similar, pero podemos apreciar que los valores tienden a concetrarse en mayor medida en el centro de la gráfica. De esta manera, podemos intuir que se “corrige” un poco el ligero problema de heterocedasticidad que podíamos haber tenido antes.</p>
<p>De todas formas, vamos a verlo con el test Breusch-Pagan</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  modelo_multiple5.1
BP = 1.3407, df = 4, p-value = 0.8544</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  modelo_multiple5.6
BP = 2.6743, df = 5, p-value = 0.75</code></pre>
</div>
</div>
<p>Como ambos p-valores son mucho mayores que 0.05, concluimos que no hay diferencia significativa a pesar del ligero aporte que se haya podido dar al modelo.</p>
</section>
<section id="estudio-gráfico-sobre-la-causa-de-la-heterocedasticidad" class="level2">
<h2 class="anchored" data-anchor-id="estudio-gráfico-sobre-la-causa-de-la-heterocedasticidad">7. Estudio gráfico sobre la causa de la heterocedasticidad</h2>
<p>Tomamos en primer lugar los residuos estandarizados.</p>
<p>Ahora, vamos a ver si la heterocedasticidad depende de la fatiga</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-85-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los valores aparecen de manera uniforme sin patrones claros, por lo que los residuos de los jugadores con altos valores de fatiga no parecen sufrir de heterocedasticidad.</p>
<p>Por otro lado, vamos a ver si esta depende de las horas de sueño</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-86-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los residuos de jugadores con pocas horas de sueño aparecen más dispersos que los valores de la anterior gráfica.</p>
<p>Por tanto, podemos concluir que el efecto de la heterocedasticidad es más acusado para jugadores con pocas horas de sueño que para aquellos con mucha fatiga.</p>
</section>
<section id="cómo-afecta-la-heterocedasticidad" class="level2">
<h2 class="anchored" data-anchor-id="cómo-afecta-la-heterocedasticidad">8. Cómo afecta la heterocedasticidad</h2>
<p>La heterocedasticidad es, por definición, el fenómeno ocurrido cuando la varianza de los errores cambia según los valores de los predictores.</p>
<p>En una primera instancia, esto implica que los estimadores de los coeficientes no sean de mínima varianza, perdiendo así eficacia.</p>
<p>De esta manera, la varianza obtenida a partir de los estimadores a la hora de hacer intervalos de confianza, se estimará incorrectamente; derivando en intervalos de confianza que no reflejen correctamente el umbral real.</p>
<p>Con respecto a los tests de significación, tenemos un problema similar. En este caso, lo que cambiará será el p-valor de los mismos. En particular, en caso de sobreestimar varianza, tendremos riesgos de encontrar falsos negativos (es decir, de no encontrar un efecto real) , y en caso de subestimar varianza estará el riesgo de encontrar falsos positivos (es decir, rechazar la hipótesis nula siendo cierta).</p>
</section>
<section id="posibilidad-de-recurrir-a-un-glm-con-varianza-distinta-a-la-normal-para-modelar-performance_index" class="level2">
<h2 class="anchored" data-anchor-id="posibilidad-de-recurrir-a-un-glm-con-varianza-distinta-a-la-normal-para-modelar-performance_index">9. Posibilidad de recurrir a un GLM con varianza distinta a la normal para modelar <em>performance_index</em></h2>
<p>Sí, en algunos casos, recurrir a un GLM con varianza distinta a la normal puede ser conveniente. Esto es debido a que, usando un GLM adecuado, podemos separar la media de la varianza, permitiendo mejorar la eficiencia de los intervalos de confianza y tests.</p>
<p>Es decir, el uso de los GLM puede ayudar en caso de problemas con heterocedasticidad marcada, valores extremos o asimetría y restricciones de la variable.</p>
</section>
<section id="estrategia-más-adecuada" class="level2">
<h2 class="anchored" data-anchor-id="estrategia-más-adecuada">10. Estrategia más adecuada</h2>
<p>En este caso, lo mejor será dejar el modelo tal cual está, ya que no tenemos grandes problemas de heterocedasticidad que puedan dar lugar a errores posteriores con tests o intervalos de confianza.</p>
<p>De esta manera, al no haber heterocedasticidad marcada ni una gran diferencia entre residuos normales y robustos, lo mejor será mantener la regresión múltiple estándar.</p>
</section>
</section>
<section id="modelos-glm" class="level1">
<h1>6. MODELOS GLM</h1>
<section id="modelo-de-poisson-para-injury_count" class="level2">
<h2 class="anchored" data-anchor-id="modelo-de-poisson-para-injury_count">1. Modelo de Poisson para <em>injury_count</em></h2>
<p>Vamos a ajustar un modelo de Poisson para explicar la variable <em>injury_count</em> a partir de <em>training_hours</em> y <em>fatigue</em>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = injuries_count ~ training_hours + fatigue, family = poisson(link = "log"), 
    data = datos)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    -1.999903   0.441224  -4.533 5.83e-06 ***
training_hours  0.026397   0.023497   1.123   0.2613    
fatigue         0.010357   0.005342   1.939   0.0525 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 501.36  on 510  degrees of freedom
Residual deviance: 496.44  on 508  degrees of freedom
  (10 observations deleted due to missingness)
AIC: 777.75

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>Con la salida del modelo, vamos a ver si los coeficientes son significativos. Como el p-valor del intercepto es muy bajo (&lt;0.05), significa que es significativo. Por el contrario, los otros coeficientes no lo serán, ya que su p-valor asociado es &gt;0.05.</p>
</section>
<section id="existencia-de-sobre-dispersión-en-el-modelo-de-poisson" class="level2">
<h2 class="anchored" data-anchor-id="existencia-de-sobre-dispersión-en-el-modelo-de-poisson">2. Existencia de sobre-dispersión en el modelo de Poisson</h2>
<p>El índice de dispersión viene determinado por el cociente entre la desviación residual y los grados de libertad de los residuos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9772406</code></pre>
</div>
</div>
<p>En este caso, el índice de dispersión es 0.9772406. De esta manera, al aproximarse a 1, la dispersión que presenta el modelo es adecuada.</p>
</section>
<section id="modelo-de-binomial-negativa" class="level2">
<h2 class="anchored" data-anchor-id="modelo-de-binomial-negativa">3. Modelo de binomial negativa</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = injuries_count ~ training_hours + fatigue, data = datos, 
    init.theta = 1.065540961, link = log)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    -1.905753   0.501522  -3.800 0.000145 ***
training_hours  0.022722   0.026949   0.843 0.399139    
fatigue         0.009498   0.006122   1.552 0.120779    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(1.0655) family taken to be 1)

    Null deviance: 375.61  on 510  degrees of freedom
Residual deviance: 372.22  on 508  degrees of freedom
  (10 observations deleted due to missingness)
AIC: 764.42

Number of Fisher Scoring iterations: 1

              Theta:  1.066 
          Std. Err.:  0.376 

 2 x log-likelihood:  -756.420 </code></pre>
</div>
</div>
<p>Para ver cual es mejor, comapararemos el AIC de los modelos</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>               df      AIC
modelo_poisson  3 777.7540
modelo_nb       4 764.4201</code></pre>
</div>
</div>
<p>Ambos valores son similares, por lo que los modelos también lo serán. Sin embargo, el AIC del modelo binomial negativo es algo menor, por lo que el modelo será algo mejor que el modelo de Poisson.</p>
</section>
<section id="comparación-de-la-devianza-residual-de-los-modelos-de-poisson-y-negbin" class="level2">
<h2 class="anchored" data-anchor-id="comparación-de-la-devianza-residual-de-los-modelos-de-poisson-y-negbin">4. Comparación de la devianza residual de los modelos de Poisson y NegBin</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Poisson:    deviance = 496.4382   df.resid = 508 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>NegBin:     deviance = 372.2175   df.resid = 508 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Poisson: dev/df = 0.9772406 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>NegBin:  dev/df = 0.7327116 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Diferencia de devianzas (Poisson - NegBin) = 124.2207 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio test

Model 1: injuries_count ~ training_hours + fatigue
Model 2: injuries_count ~ training_hours + fatigue
  #Df  LogLik Df  Chisq Pr(&gt;Chisq)    
1   3 -385.88                         
2   4 -378.21  1 15.334  9.009e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Vemos en la salida del test que el modelo NegBin tiene una devianza residual mucho menor que el modelo de Poisson. Esto implica que el modelo NegBin tiene un mejor ajuste que el de Poisson. Para confirmarlo, podemos ver también los ratios de devianza por cada grado de libertad (índices de devianza). Vemos que también es menor para el modelo NegBin, lo que cuadra con el resultado defendido.</p>
<p>Finalmente, con el <em>lrtest</em>, confirmamos que el modelo NegBin es mejor que el de Poisson, al tener un p-valor menor que 0.05.</p>
</section>
<section id="ratios-para-modelo-de-regresión-logística" class="level2">
<h2 class="anchored" data-anchor-id="ratios-para-modelo-de-regresión-logística">5. Ratios para modelo de regresión logística</h2>
<p>En primer lugar, creamos el modelo de regresión. Usaremos el conjunto de datos <em>datos_imputados</em>, para que no haya problemas posteriores con los valores faltantes.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = starter ~ training_hours + match_intensity + agility_time, 
    family = binomial(link = "logit"), data = datos_imputados)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)     -7.45138    4.30586  -1.731   0.0835 .
training_hours   0.08850    0.09273   0.954   0.3399  
match_intensity  0.04883    0.02710   1.802   0.0715 .
agility_time    -0.10927    0.30685  -0.356   0.7218  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 106.64  on 520  degrees of freedom
Residual deviance: 102.07  on 517  degrees of freedom
AIC: 110.07

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<p>A continuación, vamos a calcular los ratios para el modelo</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept)  training_hours match_intensity    agility_time 
   0.0005806386    1.0925322028    1.0500432749    0.8964902170 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                       2.5 %   97.5 %
(Intercept)     9.816988e-08 2.383231
training_hours  9.105728e-01 1.310917
match_intensity 9.965246e-01 1.109307
agility_time    4.887145e-01 1.638839</code></pre>
</div>
</div>
<p>Teniendo los ratios, vemos que las variables <em>training_hours</em> y <em>match_intensity</em> incrementan la posibilidad de ser jugador titular. Por otro lado, vemos que la variable <em>agility_time</em> tiene el efecto contrario. Es decir, esta variable disminiuye la probabilidad de ser titular en un partido.</p>
<p>Sin embargo, vemos que ninguna de las variables tiene un efecto significativo sobre la posibilidad de ser titular en un partido. Esto se debe a que los intervalos de confianza de todas las variables incluyen el valor 1. De esta manera, a pesar de poder influir, no lo hacen de forma estadísticamente significativa.</p>
</section>
<section id="representación-de-curva-roc-y-cálculo-del-auc" class="level2">
<h2 class="anchored" data-anchor-id="representación-de-curva-roc-y-cálculo-del-auc">6. Representación de curva ROC y cálculo del AUC</h2>
<p>En primer lugar, vamos a calcular las probabilidades predichas</p>
<p>A continuación, podemos crear la curva ROC.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-95-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Por otro lado, calcularemos el AUC.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.6439</code></pre>
</div>
</div>
<p>Vamos a añadirlo a la gráfica para ver todos los resultados en la misma iamgen y poder interpretarlos.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica1_estadistica_files/figure-html/unnamed-chunk-97-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>De esta manera, vemos que el área bajo la curva ROC es de 0.64. Esto implica una discriminación baja, la cual puede ser mejorable, pero ya supone un modelo no aleatorio. De esta manera, podemos distinguir en cierto modo patrones que determinarán la titularidad o la suplencia de los jugadores atendiendo a las variables que tenemos en la base de datos.</p>
</section>
<section id="modelo-binomial-logit-para-la-tasa-de-acierto-en-pases" class="level2">
<h2 class="anchored" data-anchor-id="modelo-binomial-logit-para-la-tasa-de-acierto-en-pases">7. Modelo binomial logit para la tasa de acierto en pases</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(passes_success, passes_attempted - passes_success) ~ 
    agility_time + fatigue + position, family = binomial(link = "logit"), 
    data = datos)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         5.008381   0.153538  32.620  &lt; 2e-16 ***
agility_time       -0.365756   0.012438 -29.407  &lt; 2e-16 ***
fatigue            -0.019189   0.000857 -22.389  &lt; 2e-16 ***
positionforward    -0.042252   0.032664  -1.294    0.196    
positiongoalkeeper -0.050097   0.050761  -0.987    0.324    
positionmidfielder  0.158213   0.029334   5.393 6.91e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2290.47  on 510  degrees of freedom
Residual deviance:  876.47  on 505  degrees of freedom
  (10 observations deleted due to missingness)
AIC: 3056.8

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Con la salida del modelo, vemos que la tasa de acierto en pases viene determinada por varios factores. En particular, la variable <em>agility_time</em> influye muy negativamente en la tasa de acierto de pases. Por otro lado, la variable <em>fatigue</em> influye también negativamente, pero con un peso mucho menor.</p>
<p>Por otro lado, vemos que el efecto de la posición no tiene por qué influir de forma estadísticamente significativa, ya que el hecho de ser portero o delantero no explica la variación de la tasa de pases (p-valores muy elevados).</p>
<p>Finalmente, encontramos el único factor que influye positivamente, con un peso bastante alto, y es el hecho de ser centrocampista. Esta es la única posición que explica correctamente la variación de la tasa de acierto en pases.</p>
</section>
<section id="qué-posición-tiene-mayor-probabilidad-de-completar-pases-exitosos" class="level2">
<h2 class="anchored" data-anchor-id="qué-posición-tiene-mayor-probabilidad-de-completar-pases-exitosos">8. Qué posición tiene mayor probabilidad de completar pases exitosos</h2>
<p>Según la salida del modelo anterior, tal y como ya hemos comentado, la única posición que influye positivamente en la tasa de pases acertados es la de centrocampista.</p>
<p>De esta manera, la posición con mayor probabilidad de completar pases exitosos, será la de centrocampista.</p>
</section>
<section id="modelo-logístico-incluyendo-sleep_hours" class="level2">
<h2 class="anchored" data-anchor-id="modelo-logístico-incluyendo-sleep_hours">9. Modelo logístico incluyendo sleep_hours</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = starter ~ sleep_group, family = binomial(link = "logit"), 
    data = datos)

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -3.9703     1.0093  -3.934 8.36e-05 ***
sleep_group≥6h   0.1592     1.0587   0.150     0.88    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 106.42  on 515  degrees of freedom
Residual deviance: 106.40  on 514  degrees of freedom
  (5 observations deleted due to missingness)
AIC: 110.4

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>Vemos que el hecho de haber dormido más de 6 horas parece que influye positivamente en la probabilidad de ser titular. Sin embargo, vemos que el p-valor del coeficiente asociado a <em>sleep_group</em> es muy elevado. De esta manera, es una variable que no explica bien la variabilidad de la variable <em>starter</em>.</p>
<p>Así, podemos concliur que no hay evidencia significativa de que el descanso de los jugadores influya en la posibilidad de ser titular.</p>
</section>
<section id="ventajas-de-usar-glm-frente-a-la-regresión-lineal-para-modelar-variables-como-lesiones-titularidad-o-éxito-en-pases." class="level2">
<h2 class="anchored" data-anchor-id="ventajas-de-usar-glm-frente-a-la-regresión-lineal-para-modelar-variables-como-lesiones-titularidad-o-éxito-en-pases.">10. Ventajas de usar GLM frente a la regresión lineal para modelar variables como lesiones, titularidad o éxito en pases.</h2>
<p>El hecho de usar GLM supone varias ventajas frente a la regresión lineal para modelar este tipo de variables. Entre estas ventajas, encontramos el hecho de que permite modelar correctamente la distribución correcta de la variable dependiente, así como el hecho de trabajar con ratios muy útiles para variables binarias (como hemos hecho con la variable <em>starter</em>).</p>
<p>Además, el hecho de usar GLM evita problemas de predicciones fuera de rango y errores de homocedasticidad, así como permite ajustar la varianza que depende de la media.</p>
</section>
</section>
<section id="interacciones" class="level1">
<h1>7. INTERACCIONES</h1>
<section id="ajuste-de-modelo-lineal-para-performance_index-en-función-de-training_hoursxmatch_intensity" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-de-modelo-lineal-para-performance_index-en-función-de-training_hoursxmatch_intensity">1. Ajuste de modelo lineal para <em>performance_index</em> en función de <em>training_hours</em>X<em>match_intensity</em></h2>
<p>Ajustamos el modelo de interacción.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = performance_index ~ training_hours * match_intensity, 
    data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-24.0955  -5.0763   0.4258   5.9974  23.1038 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    41.999437   9.305982   4.513 7.93e-06 ***
training_hours                  0.902878   0.655718   1.377    0.169    
match_intensity                -0.084861   0.129677  -0.654    0.513    
training_hours:match_intensity  0.011328   0.009122   1.242    0.215    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.848 on 512 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.3472,    Adjusted R-squared:  0.3433 
F-statistic: 90.75 on 3 and 512 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>